apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-db-depl
spec:
  selector:
    matchLabels:
      app: market-db
  template:
    metadata:
      labels:
        app: market-db
    spec:
      containers:
      - name: market-db
        image: mysql:8.0.26
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: flaskmarket
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:              
              name: mysql-secret
              key: app-db-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-db-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:              
              name: mysql-secret
              key: mysql-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: market-db-service
spec:
  selector:
    app: market-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306


